name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Kör workflow när du pushar till denna branch

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Viktigt för OIDC
      contents: read # För att läsa repo-filer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/316754181932/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "ci-deployer@training-app-7dc19.iam.gserviceaccount.com"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
